### PR TITLE
fix issue #48

### PR DESCRIPTION
**Pull request by gucong3000**

### CODE REVIEW

**Comment by gucong3000** [comment]
Any plan?

**Comment by bcoe** [comment]
@gucong3000 I don't like that this removes error checking for the syntax in JSON files, have you tried this:

```js
require('y18n')({updateFiles: false})
```

This will prevent a y18n from populating a configuration file when a string is missing, which might be the appropriate behavior in your case?

**Comment by bcoe** [comment]
I'd be tempted to default the value of `updateFiles` to `false`, and would happily accept a patch for this.

**Comment by gucong3000** [comment]
@bcoe 
>I don't like that this removes error checking for the syntax in JSON files

It still checking for the syntax in JSON files, but empty files.

**Comment by bcoe** [comment]
@gucong3000 did you have a chance to try setting `updateFiles` to `false; in a perfect world, I don't think we should be writing empty files to disk.

**Comment by gucong3000** [comment]
> did you have a chance to try setting `updateFiles` to `false;

Yes, `updateFiles` is work fine for `eclint`

**Comment by gucong3000** [comment]
> I don't think we should be writing empty files to disk.

You are right.

**Comment by bcoe** [comment]
@gucong3000 I think that, rather than protect against this edge-case (which should only happen if an app quits unexpectedly) I'd rather that we default `updateFiles` to `false`; so that people only enable this feature when they're developing an app.

**Pull request closed without merging**
