### PR TITLE
Closes #20

### LINKED ISSUE #20: Published package should not include tests
The npm package that is published should not include tests.

Background: running into problems in a project I'm working on that uses [flow](http://flowtype.org), which fails (understandably) when trying to process invalid JSON files that are in the `test` directory of this package.

Simple solution is to add a `.npmignore` file containing `test` (per [npm docs: keeping files out of your package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)).

### PR DESCRIPTION
**Pull request by mcalthrop**
Add `.npmignore` file - contains one entry: the `test` directory

### CODE REVIEW

**Comment by mcalthrop** [comment]
Note: I haven't bumped the version in `package.json` – leaving that to the repo owner to do when ready.

**Comment by bcoe** [comment]
@mcalthrop perhaps we should switch to using the `files` stanza in `package.json` (like in `yargs/yargs`) rather than introducing a `.npmignore`?

**Comment by nexdrew** [comment]
I like that idea better. :+1:

**Comment by mcalthrop** [comment]
@bcoe: thanks, good call – have updated the PR. :smile_cat:

**Comment by mcalthrop** [comment]
The [build failed](https://travis-ci.org/yargs/y18n/jobs/115815782), but as far as I can see, it's not related to changes in this PR.

**Comment by bcoe** [comment]
@mcalthrop thank you for the contribution \o/

**Pull request merged**
