### PR TITLE
fix: address prototype pollution issue

### PR DESCRIPTION
**Pull request by bcoe**
@po6ix @joaogmauricio I appreciate the vulnerability report, I believe this addresses the problem (_let me know if you can confirm). _Also let me know if you can think of any additional regression tests._

---

@JamieSlome, @alromh87, I like the idea of **huntr**, I'd rather have a company submit a patch than simply notify me of a CVE. #107 was just not inline with how I've been addressing this issue elsewhere in the yargs codebase.

CC: @ljharb 
Fixes: #96

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by JamieSlome** [comment]
@bcoe - that is great to hear - we'd love to work with you to get fixes into the repository in the future. Would you be available to discuss this further together?

**Comment by bcoe** [comment]
@JamieSlome happy to discuss more, email is a good place to start as I'm pretty full of meetings over the next few weeks.

**Comment by JamieSlome** [comment]
@bcoe - I will shoot over an e-mail to you today!

**Comment by stof** [comment]
@bcoe will this be backported in the 4.x major version ? webpack 4 depends on a version of cacache which uses `y18n` 4.x

**Comment by lizzi2122** [comment]
TEST

**Review by Muhammadariesta — COMMENTED** [review]
foo@bar.com

**Pull request merged**
